---
- name: Create docker directories
  become: true
  file: path="{{item}}" state=directory mode=0755
  with_items:
  - /etc/systemd/system/docker.service.d

- set_fact:
    lagoon_docker_no_proxy: "{{lagoon_docker_proxy.no_proxy | replace('[NODES_IPS]',lagoon_docker_nodes_ip)}}"

- name: Install proxies
  become: true
  template:
    src: templates/proxy.conf
    dest: /etc/systemd/system/docker.service.d
